# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from screeninfo import get_monitors

dir = os.getcwd().replace('\\','/')

lnks, icons = [],[]

positions = []

def load():
    global lnks, icons
    lnks, icons = [],[]

    with open('applist.txt','r') as f:
        t = f.readlines()
        #print(t)
    for i in range(len(t)):
        s = t[i].strip().split('||')
        lnks.append(s[0])
        icons.append(s[1])

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        global positions
        positions = []
        MainWindow.setObjectName("MainWindow")
        #print(len(get_monitors()))
        for m in get_monitors():
            positions.append([m.x,m.y,m.width,m.height])

        
        MainWindow.setWindowOpacity(1.0)
        flags = QtCore.Qt.WindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)# if self.on_top else QtCore.Qt.FramelessWindowHint)
        MainWindow.setWindowFlags(flags)
        MainWindow.setAttribute(QtCore.Qt.WA_NoSystemBackground, True)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground, True)
        self.buttons = []
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.xy = [0,0]
        '''
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFlat(True)
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);background-image : url(%s);"%(dir+'/icons/bigsur_finder.png'))
        self.pushButton.clicked.connect(self.runexplorer)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 0, 71, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(lambda:self.hidingwindow(MainWindow))
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 0, 71, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 0, 71, 71))
        self.pushButton_4.setObjectName("pushButton_4")'''
        MainWindow.setCentralWidget(self.centralwidget)
        self.btnrenderer(MainWindow)

        #self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.show() #나중에 그걸로 바꿀것. 마우스가 화면아래로 오는지 감지해서 하는 그거

    def btnrenderer(self, MainWindow):
        load()
        #print(lnks, icons)
        MainWindow.resize(len(lnks)*70, 70)
        for i in range(len(lnks)):
            b = 0
            b = QtWidgets.QPushButton(self.centralwidget)
            b.setGeometry(QtCore.QRect(i*70, 0, 71, 71))
            b.setObjectName("pushButton_"+str(i)) if i!=0 else b.setObjectName("pushButton")
            b.setFlat(True)
            b.setStyleSheet("background-color: rgba(255, 255, 255, 0);background-image : url(%s);"%(dir+'/'+icons[i]))
            #func = lambda:os.startfile(dir+'/'+lnks[i])
            #b.clicked.connect(lambda:self.whichbutton(b))
            self.buttons.append(b)
        for i in range(len(lnks)):
        #    print(self.buttons[i].objectName())
        #    print(lnks[i])
        #    self.buttons[i].clicked.connect(lambda:os.startfile(dir+'/'+lnks[i]))
            try:
                eval('self.buttons[%d].clicked.connect(lambda:os.startfile(dir+"/"+lnks[%d]))'%(i,i))
            except:
                pass
        #self.buttons[0].clicked.connect(lambda:os.startfile(dir+'/'+lnks[0]))
        #self.buttons[1].clicked.connect(lambda:os.startfile(dir+'/'+lnks[1]))

    #def retranslateUi(self):
        #_translate = QtCore.QCoreApplication.translate
        #self.pushButton.setText(_translate("MainWindow", "icon"))
        #self.pushButton_2.setText(_translate("MainWindow", "icon"))
        #self.pushButton_3.setText(_translate("MainWindow", "icon"))
        #self.pushButton_4.setText(_translate("MainWindow", "icon"))

    def hidingwindow(self, MainWindow):
        MainWindow.hide()
        exit()
        #print('clicked!')
    def runexplorer(self):
        os.startfile(dir+'/lnks/explorer.lnk')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    #MainWindow.show()
    sys.exit(app.exec_())
